
name: 'jaffle_shop'
version: 1.0.0

config-version: 2

vars:
  my_var: 1
  another_var: true

  profile: 'jaffle_shop'
  source-paths: ["models"]
  analysis-paths: ["analysis"]
  test-paths: ["tests"]
  data-paths: ["data"]
  macro-paths: ["macros"]

  target-path: "target"
  clean-targets:
      - "target"
      - "dbt_modules"
      - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]

# comment 2