version: 2

sources:
   - name: analytics
     database: dbt

     freshness:
       warn_after: {count: 1, period: day}
       error_after: {count: 1000000, period: day}
     tables:
       - name: raw_customers
       - name: raw_orders
         loaded_at_field: order_date::timestamp
       - name: raw_payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

exposures:

   - name: stg_orders
     type: dashboard
     maturity: medium
     url: https://github.com/eiof/jaffle_shop
     description: :D

     depends_on:
       - ref('stg_orders')

     owner:
       name: eiof
       email: matt@fishtownanalytics.com